#!/usr/bin/env node
// Generates one memorandum and four decks per country, per language.
//   node build.mjs            → writes into ./dist
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { COUNTRIES } from './src/data.mjs';
import { L } from './src/strings.mjs';
import { buildDoc } from './src/doc.mjs';
import { DECKS } from './src/decks.mjs';
import { buildAppendix, hasAppendix } from './src/appendix.mjs';

const root = dirname(fileURLToPath(import.meta.url));
const dist = join(root, 'dist');

const written = [];
function out(rel, html) {
  const p = join(dist, rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, html, 'utf8');
  written.push([rel, Buffer.byteLength(html)]);
}

const NAMES = {
  en: { doc: 'memorandum', stablecoin: 'deck-stablecoin', gaming: 'deck-gaming', hardware: 'deck-hardware', schools: 'deck-schools' },
};

for (const c of COUNTRIES) {
  for (const lang of c.langs) {
    const l = L(lang, c);
    const sfx = lang === 'en' ? '' : `.${lang}`;
    out(`${c.cc}/memorandum${sfx}.html`, buildDoc(c, l));
    if (lang === 'en' && c.cc === 'kg') {
      out(`${c.cc}/memorandum.en.html`, buildDoc(c, l));
    }
    for (const [key, fn] of Object.entries(DECKS)) {
      out(`${c.cc}/deck-${key}${sfx}.html`, fn(c, l));
    }
    if (lang === 'ru' && hasAppendix(c.cc)) {
      out(`${c.cc}/appendix-bond.ru.html`, buildAppendix(c, l));
    }
  }
}

/* ---- index ---- */
const rows = COUNTRIES.map(c => {
  const cells = c.langs.map(lang => {
    const sfx = lang === 'en' ? '' : `.${lang}`;
    const tag = lang.toUpperCase();
    return `<tr>
      <td class="cc">${c.cc === COUNTRIES[0].cc || lang === c.langs[0] ? `<b>${c.country}</b>` : ''} <span class="lg">${tag}</span></td>
      <td><a href="${c.cc}/memorandum${sfx}.html">Memorandum</a>${lang === 'ru' && hasAppendix(c.cc) ? ` · <a href="${c.cc}/appendix-bond.ru.html">Приложение A (нота)</a>` : ''}</td>
      <td><a href="${c.cc}/deck-stablecoin${sfx}.html">Stablecoin</a></td>
      <td><a href="${c.cc}/deck-gaming${sfx}.html">Gaming clubs</a></td>
      <td><a href="${c.cc}/deck-hardware${sfx}.html">Hardware</a></td>
      <td><a href="${c.cc}/deck-schools${sfx}.html">Schools</a></td>
    </tr>`;
  }).join('');
  return cells;
}).join('');

out('index.html', `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Country programme materials</title>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
<style>
body{font-family:Inter,system-ui,sans-serif;margin:0;padding:60px 24px;background:#f4f4f7;color:#0b0b0c}
main{max-width:960px;margin:0 auto}
h1{font-size:30px;letter-spacing:-1px;margin:0 0 6px}
p.s{color:#6b6b76;margin:0 0 32px;max-width:620px;line-height:1.5}
table{width:100%;border-collapse:collapse;background:#fff;border-radius:8px;overflow:hidden}
td{padding:12px 14px;border-bottom:1px solid #e7e7ee;font-size:14px}
tr:last-child td{border-bottom:0}
td.cc{white-space:nowrap}
.lg{font-size:10px;font-weight:800;letter-spacing:1px;color:#fff;background:#0f7361;border-radius:3px;padding:2px 5px;vertical-align:2px}
a{color:#0f7361;text-decoration:none;font-weight:600}a:hover{text-decoration:underline}
.n{margin-top:28px;font-size:12.5px;color:#6b6b76;line-height:1.6;max-width:680px}
</style></head><body><main>
<h1>Country programme materials</h1>
<p class="s">One memorandum and four proposal decks per country. Decks print to 16:9 slides; the memorandum prints to A4. Use the browser's Print dialog and choose "Save as PDF" with background graphics enabled.</p>
<table>${rows}</table>
<p class="n">Generated by <code>build.mjs</code> — edit <code>src/data.mjs</code> (country facts) or <code>src/strings.mjs</code> (copy) and re-run <code>node build.mjs</code>. All figures are internal modelling estimates, not audited statistics. Contact lines on the closing slides are placeholders (⟨name · e-mail · telephone⟩) and need filling in before these go out.</p>
</main></body></html>`);

console.log(`Wrote ${written.length} files to dist/`);
for (const [f, b] of written) console.log(`  ${f.padEnd(34)} ${(b / 1024).toFixed(0)} KB`);
