// Copy for the regional pages, one table per language.
//
// Placeholders: {country} {coin} {landmark}. English is the reference table and
// the fallback for any key a translation is missing, so a partially translated
// language still renders a complete page.

const T = {
  en: {
    navCompute:'Compute', navCoin:'{coin}', navCountry:'{country}', navDai:'DAI', navWallet:'Wallet', navMiner:'DAI Miner',
    heroTitle:'Decentralized AI compute, paid in {coin}',
    heroLede:'Your machine answers AI tasks for the network and is paid in {coin} — no data centre, no cloud contract, no permission needed.',
    s1Eyebrow:'What this is', s1Title:'A network that computes.',
    s1aT:'Decentralized', s1aD:'Independent nodes, peer to peer. No company owns the mesh and there is no central switch to flip.',
    s1bT:'Encrypted & sovereign', s1bD:'You hold the keys. Chat is end-to-end encrypted and your data never leaves your terms.',
    s1cT:'Pay per use', s1cD:'Metered per AI token with a hard budget per job. Unused budget is returned.',
    s2Eyebrow:'The payment layer', s2Title:'Settled in {coin}.',
    s2aT:'{coin}', s2aD:'The local rail. Value moves in the currency people actually earn and spend.',
    s2bT:'DAI provides the compute', s2bD:'Decentralized AI compute for that economy, priced and settled locally.',
    s3Eyebrow:'Why here', s3Title:'Built in {country}.',
    s3aT:'Affordable power', s3aD:'Electricity is the real input cost of AI compute, and here it is cheap enough to leave a margin.',
    s3bT:'People who build', s3bD:'A young, technical workforce that can run nodes and write the skills that run on them.',
    s3cT:'Local demand', s3cD:'AI priced in local money, reachable without a foreign card or a foreign bank.',
    s3dT:'Sovereign by design', s3dD:'The coin stays yours. The network settles it without asking anyone for permission.',
    s4Eyebrow:'The local market', s4Title:'{coin} buys compute.',
    s4Lede:'Hard currency settles into {coin} — and {coin} buys AI compute, local talent and local experience in {country}.',
    s4In:'Fiat in', s4Rail:'{country} stablecoin', s4Out:'What you get',
    s4o1:'AI compute', s4o2:'Local talent', s4o3:'Experience',
    s5Eyebrow:'Exchange', s5Title:'Trade it peer to peer.',
    s5Lede:'Swap USDT, {coin} and the other compute coins on the open P2P market. Both legs settle on chain in seconds.',
    s5Cta:'Open the P2P market',
    s6Eyebrow:'Get started', s6Title:'Put your machine to work.',
    s6Lede:'Run a node. Earn {coin}.',
    s6a:'Run a node', s6b:'Read the docs',
    footTag:'Decentralized AI compute for the {coin} economy · {country}',
    sceneCap:'{landmark}',
  },

  ky: {
    navCompute:'Эсептөө', navCoin:'{coin}', navCountry:'Кыргызстан', navDai:'DAI', navWallet:'Капчык', navMiner:'DAI Майнер',
    heroTitle:'Борборсуздандырылган AI эсептөө, {coin} менен төлөнөт',
    heroLede:'Сиздин компьютериңиз тармак үчүн AI тапшырмаларын аткарып, {coin} менен акы алат — дата борбору жок, булут келишими жок, уруксат сурабай.',
    s1Eyebrow:'Бул эмне', s1Title:'Эсептеген тармак.',
    s1aT:'Борборсуздандырылган', s1aD:'Көз карандысыз түйүндөр, теңтуштан теңтушка. Тармакка эч бир компания ээлик кылбайт жана аны өчүрө турган борбордук ачкыч жок.',
    s1bT:'Шифрленген жана эгемен', s1bD:'Ачкычтар сизде. Маек учтан учка шифрленген, маалыматыңыз сиздин шартыңыздан чыкпайт.',
    s1cT:'Колдонгонго жараша төлөм', s1cD:'Ар бир AI токенине эсептелет, ар бир тапшырмага так бюджет менен. Колдонулбаган бюджет кайтарылат.',
    s2Eyebrow:'Төлөм катмары', s2Title:'{coin} менен эсептешүү.',
    s2aT:'{coin}', s2aD:'Жергиликтүү рельс. Наркы адамдар чындап тапкан жана коротгон валютада жүрөт.',
    s2bT:'DAI эсептөөнү берет', s2bD:'Ошол экономика үчүн борборсуздандырылган AI эсептөө — жергиликтүү бааланат жана эсептешет.',
    s3Eyebrow:'Эмне үчүн бул жерде', s3Title:'Кыргызстанда курулган.',
    s3aT:'Арзан энергия', s3aD:'Электр энергиясы — AI эсептөөнүн негизги чыгымы, бул жерде ал майнерге пайда калтырарлык арзан.',
    s3bT:'Куруучу адамдар', s3bD:'Түйүндөрдү иштетип, аларда иштеген жөндөмдөрдү жаза алган жаш, техникалык жамаат.',
    s3cT:'Жергиликтүү суроо-талап', s3cD:'AI жергиликтүү акчада бааланат — чет элдик карта же банк талап кылынбайт.',
    s3dT:'Түзүлүшү боюнча эгемен', s3dD:'Монета сиздики бойдон калат. Тармак аны эч кимден уруксат сурабай эсептешет.',
    s4Eyebrow:'Жергиликтүү базар', s4Title:'{coin} эсептөө сатып алат.',
    s4Lede:'Катуу валюта {coin} болуп эсептешет — ал эми {coin} Кыргызстанда AI эсептөөнү, жергиликтүү таланттарды жана тажрыйбаны сатып алат.',
    s4In:'Кирген валюта', s4Rail:'Кыргызстандын стейблкоини', s4Out:'Сиз эмне аласыз',
    s4o1:'AI эсептөө', s4o2:'Жергиликтүү талант', s4o3:'Тажрыйба',
    s5Eyebrow:'Биржа', s5Title:'Теңтуштан теңтушка соода.',
    s5Lede:'Ачык P2P базарында USDT, {coin} жана башка эсептөө монеталарын алмаштырыңыз. Эки тарап тең чынжырда секунданын ичинде эсептешет.',
    s5Cta:'P2P базарын ачуу',
    s6Eyebrow:'Баштоо', s6Title:'Компьютериңизди иштетиңиз.',
    s6Lede:'Түйүн иштетиңиз. {coin} табыңыз.',
    s6a:'Түйүн иштетүү', s6b:'Документтерди окуу',
    footTag:'{coin} экономикасы үчүн борборсуздандырылган AI эсептөө · Кыргызстан',
    sceneCap:'Ысык-Көл жана Тянь-Шань',
  },

  am: {
    navCompute:'ስሌት', navCoin:'{coin}', navCountry:'ኢትዮጵያ', navDai:'DAI', navWallet:'ቦርሳ', navMiner:'DAI ማዕድን',
    heroTitle:'ያልተማከለ የAI ስሌት፣ በ{coin} ይከፈላል',
    heroLede:'ማሽንዎ ለአውታረ መረቡ የAI ተግባራትን ይሠራል እና በ{coin} ይከፈላል — ዳታ ማዕከል የለም፣ የደመና ውል የለም፣ ፈቃድ አያስፈልግም።',
    s1Eyebrow:'ይህ ምንድን ነው', s1Title:'የሚያሰላ አውታረ መረብ።',
    s1aT:'ያልተማከለ', s1aD:'ራሳቸውን የቻሉ አንጓዎች፣ ከአቻ ወደ አቻ። አውታረ መረቡን የሚይዝ ኩባንያ የለም፣ የሚዘጋ ማዕከላዊ ማብሪያም የለም።',
    s1bT:'የተመሰጠረ እና ሉዓላዊ', s1bD:'ቁልፎቹ የእርስዎ ናቸው። ውይይት ከጫፍ እስከ ጫፍ የተመሰጠረ ነው፣ መረጃዎም ከእርስዎ ውል አይወጣም።',
    s1cT:'በአጠቃቀም ይክፈሉ', s1cD:'በእያንዳንዱ የAI ቶከን ይለካል፣ ለእያንዳንዱ ሥራ ጥብቅ በጀት አለው። ያልዋለ በጀት ይመለሳል።',
    s2Eyebrow:'የክፍያ ንብርብር', s2Title:'በ{coin} ይወራረዳል።',
    s2aT:'{coin}', s2aD:'የአካባቢው መስመር። ዋጋ ሰዎች በሚያገኙትና በሚያወጡት ገንዘብ ይንቀሳቀሳል።',
    s2bT:'DAI ስሌቱን ያቀርባል', s2bD:'ለዚያ ኢኮኖሚ ያልተማከለ የAI ስሌት፣ በአካባቢው ዋጋ ተሰጥቶ ይወራረዳል።',
    s3Eyebrow:'ለምን እዚህ', s3Title:'በኢትዮጵያ የተገነባ።',
    s3aT:'ተመጣጣኝ ኃይል', s3aD:'ኤሌክትሪክ የAI ስሌት ዋና ወጪ ነው፣ እዚህ ደግሞ ትርፍ የሚያስቀር ያህል ርካሽ ነው።',
    s3bT:'የሚገነቡ ሰዎች', s3bD:'አንጓዎችን ማስኬድና በእነሱ ላይ የሚሠሩ ችሎታዎችን መጻፍ የሚችል ወጣትና ቴክኒካዊ ኃይል።',
    s3cT:'የአካባቢ ፍላጎት', s3cD:'AI በአካባቢ ገንዘብ ይተመናል — የውጭ ካርድ ወይም ባንክ ሳያስፈልግ ይደረሳል።',
    s3dT:'በንድፍ ሉዓላዊ', s3dD:'ሳንቲሙ የእርስዎ ሆኖ ይቀራል። አውታረ መረቡ ከማንም ፈቃድ ሳይጠይቅ ያወራርደዋል።',
    s4Eyebrow:'የአካባቢ ገበያ', s4Title:'{coin} ስሌት ይገዛል።',
    s4Lede:'ጠንካራ ምንዛሪ ወደ {coin} ይወራረዳል — {coin} ደግሞ በኢትዮጵያ የAI ስሌት፣ የአካባቢ ችሎታና ልምድ ይገዛል።',
    s4In:'የገባ ገንዘብ', s4Rail:'የኢትዮጵያ ስቴብልኮይን', s4Out:'የሚያገኙት',
    s4o1:'የAI ስሌት', s4o2:'የአካባቢ ችሎታ', s4o3:'ልምድ',
    s5Eyebrow:'ልውውጥ', s5Title:'ከአቻ ወደ አቻ ይገበያዩ።',
    s5Lede:'USDT፣ {coin} እና ሌሎች የስሌት ሳንቲሞችን በክፍት P2P ገበያ ይለውጡ። ሁለቱም ጎኖች በሰከንዶች ውስጥ በሰንሰለቱ ላይ ይወራረዳሉ።',
    s5Cta:'የP2P ገበያን ክፈት',
    s6Eyebrow:'ይጀምሩ', s6Title:'ማሽንዎን ሥራ ላይ ያዋሉ።',
    s6Lede:'አንጓ ያስኪዱ። {coin} ያግኙ።',
    s6a:'አንጓ ማስኬድ', s6b:'ሰነዶቹን ያንብቡ',
    footTag:'ለ{coin} ኢኮኖሚ ያልተማከለ የAI ስሌት · ኢትዮጵያ',
    sceneCap:'የሰሜን ተራሮች',
  },
  es: {
    navCompute:'Cómputo', navCoin:'{coin}', navCountry:'{country}', navDai:'DAI', navWallet:'Billetera', navMiner:'DAI Miner',
    heroTitle:'Cómputo de IA descentralizado, pagado en {coin}',
    heroLede:'Tu máquina resuelve tareas de IA para la red y cobra en {coin} — sin centro de datos, sin contrato de nube, sin pedir permiso.',
    s1Eyebrow:'Qué es esto', s1Title:'Una red que computa.',
    s1aT:'Descentralizada', s1aD:'Nodos independientes, de par a par. Ninguna empresa es dueña de la malla y no hay un interruptor central que apagar.',
    s1bT:'Cifrada y soberana', s1bD:'Las claves son tuyas. El chat va cifrado de extremo a extremo y tus datos no salen de tus términos.',
    s1cT:'Pagas por uso', s1cD:'Se mide por token de IA con un presupuesto máximo por tarea. El presupuesto no usado se devuelve.',
    s2Eyebrow:'La capa de pago', s2Title:'Liquidado en {coin}.',
    s2aT:'{coin}', s2aD:'El riel local. El valor se mueve en la moneda que la gente realmente gana y gasta.',
    s2bT:'DAI aporta el cómputo', s2bD:'Cómputo de IA descentralizado para esa economía, con precio y liquidación locales.',
    s3Eyebrow:'Por qué aquí', s3Title:'Hecho en {country}.',
    s3aT:'Energía asequible', s3aD:'La electricidad es el costo real del cómputo de IA, y aquí es lo bastante barata para dejar margen.',
    s3bT:'Gente que construye', s3bD:'Una fuerza técnica y joven capaz de operar nodos y escribir las habilidades que corren en ellos.',
    s3cT:'Demanda local', s3cD:'IA cotizada en moneda local, al alcance sin tarjeta ni banco extranjero.',
    s3dT:'Soberana por diseño', s3dD:'La moneda sigue siendo tuya. La red la liquida sin pedirle permiso a nadie.',
    s4Eyebrow:'El mercado local', s4Title:'{coin} compra cómputo.',
    s4Lede:'La divisa fuerte se liquida en {coin} — y {coin} compra cómputo de IA, talento y experiencia local en {country}.',
    s4In:'Divisa que entra', s4Rail:'Stablecoin de {country}', s4Out:'Lo que obtienes',
    s4o1:'Cómputo de IA', s4o2:'Talento local', s4o3:'Experiencia',
    s5Eyebrow:'Intercambio', s5Title:'Négocialo de par a par.',
    s5Lede:'Intercambia USDT, {coin} y las demás monedas de cómputo en el mercado P2P abierto. Ambas patas liquidan en cadena en segundos.',
    s5Cta:'Abrir el mercado P2P',
    s6Eyebrow:'Empezar', s6Title:'Pon tu máquina a trabajar.',
    s6Lede:'Corre un nodo. Gana {coin}.',
    s6a:'Correr un nodo', s6b:'Leer la documentación',
    footTag:'Cómputo de IA descentralizado para la economía {coin} · {country}',
    sceneCap:'{landmark}',
  },

  bn: {
    navCompute:'কম্পিউট', navCoin:'{coin}', navCountry:'বাংলাদেশ', navDai:'DAI', navWallet:'ওয়ালেট', navMiner:'DAI মাইনার',
    heroTitle:'বিকেন্দ্রীভূত AI কম্পিউট, {coin}-এ পরিশোধিত',
    heroLede:'আপনার মেশিন নেটওয়ার্কের জন্য AI কাজ সমাধান করে এবং {coin}-এ আয় করে — কোনো ডেটা সেন্টার নেই, কোনো ক্লাউড চুক্তি নেই, কারও অনুমতি লাগে না।',
    s1Eyebrow:'এটি কী', s1Title:'এমন এক নেটওয়ার্ক যা হিসাব করে।',
    s1aT:'বিকেন্দ্রীভূত', s1aD:'স্বাধীন নোড, পিয়ার-টু-পিয়ার। কোনো কোম্পানি এই মেশের মালিক নয়, আর বন্ধ করার মতো কোনো কেন্দ্রীয় সুইচও নেই।',
    s1bT:'এনক্রিপ্টেড ও সার্বভৌম', s1bD:'কী আপনার কাছেই থাকে। চ্যাট এন্ড-টু-এন্ড এনক্রিপ্টেড, আর আপনার ডেটা আপনার শর্তের বাইরে যায় না।',
    s1cT:'ব্যবহার অনুযায়ী পরিশোধ', s1cD:'প্রতি AI টোকেনে হিসাব হয়, প্রতিটি কাজে নির্দিষ্ট বাজেটসীমাসহ। অব্যবহৃত বাজেট ফেরত দেওয়া হয়।',
    s2Eyebrow:'পরিশোধ স্তর', s2Title:'{coin}-এ নিষ্পত্তি।',
    s2aT:'{coin}', s2aD:'স্থানীয় রেল। মূল্য চলে সেই মুদ্রায় যা মানুষ সত্যিই আয় করে ও খরচ করে।',
    s2bT:'DAI কম্পিউট সরবরাহ করে', s2bD:'সেই অর্থনীতির জন্য বিকেন্দ্রীভূত AI কম্পিউট — স্থানীয়ভাবে মূল্য নির্ধারিত ও নিষ্পন্ন।',
    s3Eyebrow:'কেন এখানে', s3Title:'বাংলাদেশে নির্মিত।',
    s3aT:'সাশ্রয়ী বিদ্যুৎ', s3aD:'বিদ্যুৎই AI কম্পিউটের প্রকৃত খরচ, আর এখানে তা যথেষ্ট সস্তা যাতে লাভ থাকে।',
    s3bT:'যারা গড়ে তোলে', s3bD:'তরুণ ও কারিগরি জনশক্তি, যারা নোড চালাতে এবং তাতে চলা স্কিল লিখতে পারে।',
    s3cT:'স্থানীয় চাহিদা', s3cD:'AI-এর দাম স্থানীয় মুদ্রায় — বিদেশি কার্ড বা ব্যাংক ছাড়াই নাগালের মধ্যে।',
    s3dT:'নকশাগতভাবে সার্বভৌম', s3dD:'কয়েন আপনারই থাকে। নেটওয়ার্ক কারও অনুমতি ছাড়াই তা নিষ্পন্ন করে।',
    s4Eyebrow:'স্থানীয় বাজার', s4Title:'{coin} দিয়ে কম্পিউট কেনা যায়।',
    s4Lede:'শক্ত মুদ্রা {coin}-এ নিষ্পন্ন হয় — আর {coin} দিয়ে বাংলাদেশে AI কম্পিউট, স্থানীয় প্রতিভা ও অভিজ্ঞতা কেনা যায়।',
    s4In:'আগত মুদ্রা', s4Rail:'বাংলাদেশের স্টেবলকয়েন', s4Out:'আপনি যা পান',
    s4o1:'AI কম্পিউট', s4o2:'স্থানীয় প্রতিভা', s4o3:'অভিজ্ঞতা',
    s5Eyebrow:'বিনিময়', s5Title:'পিয়ার-টু-পিয়ার লেনদেন করুন।',
    s5Lede:'খোলা P2P বাজারে USDT, {coin} ও অন্যান্য কম্পিউট কয়েন বিনিময় করুন। উভয় দিকই কয়েক সেকেন্ডে চেইনে নিষ্পন্ন হয়।',
    s5Cta:'P2P বাজার খুলুন',
    s6Eyebrow:'শুরু করুন', s6Title:'আপনার মেশিনকে কাজে লাগান।',
    s6Lede:'একটি নোড চালান। {coin} আয় করুন।',
    s6a:'নোড চালান', s6b:'ডকুমেন্টেশন পড়ুন',
    footTag:'{coin} অর্থনীতির জন্য বিকেন্দ্রীভূত AI কম্পিউট · বাংলাদেশ',
    sceneCap:'সুন্দরবন',
  },

  ur: {
    navCompute:'کمپیوٹ', navCoin:'{coin}', navCountry:'پاکستان', navDai:'DAI', navWallet:'والیٹ', navMiner:'DAI مائنر',
    heroTitle:'غیر مرکزی AI کمپیوٹ، {coin} میں ادائیگی',
    heroLede:'آپ کی مشین نیٹ ورک کے لیے AI کام حل کرتی ہے اور {coin} میں کماتی ہے — نہ ڈیٹا سینٹر، نہ کلاؤڈ معاہدہ، نہ کسی کی اجازت۔',
    s1Eyebrow:'یہ کیا ہے', s1Title:'ایک نیٹ ورک جو حساب کرتا ہے۔',
    s1aT:'غیر مرکزی', s1aD:'خودمختار نوڈز، پیئر ٹو پیئر۔ اس میش کا مالک کوئی کمپنی نہیں اور بند کرنے کے لیے کوئی مرکزی سوئچ نہیں۔',
    s1bT:'خفیہ اور خودمختار', s1bD:'کلیدیں آپ کے پاس ہیں۔ چیٹ اینڈ ٹو اینڈ خفیہ ہے اور آپ کا ڈیٹا آپ کی شرائط سے باہر نہیں جاتا۔',
    s1cT:'استعمال کے مطابق ادائیگی', s1cD:'ہر AI ٹوکن پر پیمائش، ہر کام کے لیے سخت بجٹ حد کے ساتھ۔ غیر استعمال شدہ بجٹ واپس ہو جاتا ہے۔',
    s2Eyebrow:'ادائیگی کی پرت', s2Title:'{coin} میں تصفیہ۔',
    s2aT:'{coin}', s2aD:'مقامی راستہ۔ قدر اُسی کرنسی میں چلتی ہے جو لوگ حقیقت میں کماتے اور خرچ کرتے ہیں۔',
    s2bT:'DAI کمپیوٹ فراہم کرتا ہے', s2bD:'اُس معیشت کے لیے غیر مرکزی AI کمپیوٹ، مقامی قیمت اور مقامی تصفیے کے ساتھ۔',
    s3Eyebrow:'یہاں کیوں', s3Title:'پاکستان میں بنایا گیا۔',
    s3aT:'سستی بجلی', s3aD:'بجلی AI کمپیوٹ کی اصل لاگت ہے، اور یہاں وہ اتنی سستی ہے کہ منافع بچ جائے۔',
    s3bT:'بنانے والے لوگ', s3bD:'ایک نوجوان، تکنیکی افرادی قوت جو نوڈز چلا سکتی ہے اور اُن پر چلنے والی اسکلز لکھ سکتی ہے۔',
    s3cT:'مقامی طلب', s3cD:'AI کی قیمت مقامی پیسے میں — بغیر کسی غیر ملکی کارڈ یا بینک کے قابلِ رسائی۔',
    s3dT:'ساخت ہی سے خودمختار', s3dD:'سکہ آپ ہی کا رہتا ہے۔ نیٹ ورک اسے کسی سے اجازت مانگے بغیر طے کرتا ہے۔',
    s4Eyebrow:'مقامی منڈی', s4Title:'{coin} سے کمپیوٹ خریدیں۔',
    s4Lede:'مضبوط کرنسی {coin} میں طے ہوتی ہے — اور {coin} سے پاکستان میں AI کمپیوٹ، مقامی ہنر اور تجربہ خریدا جاتا ہے۔',
    s4In:'آنے والی کرنسی', s4Rail:'پاکستان کا اسٹیبل کوائن', s4Out:'آپ کو کیا ملتا ہے',
    s4o1:'AI کمپیوٹ', s4o2:'مقامی ہنر', s4o3:'تجربہ',
    s5Eyebrow:'تبادلہ', s5Title:'پیئر ٹو پیئر سودا کریں۔',
    s5Lede:'کھلی P2P منڈی میں USDT، {coin} اور دیگر کمپیوٹ سکے بدلیں۔ دونوں اطراف سیکنڈوں میں چین پر طے ہو جاتی ہیں۔',
    s5Cta:'P2P منڈی کھولیں',
    s6Eyebrow:'شروع کریں', s6Title:'اپنی مشین کو کام پر لگائیں۔',
    s6Lede:'ایک نوڈ چلائیں۔ {coin} کمائیں۔',
    s6a:'نوڈ چلائیں', s6b:'دستاویزات پڑھیں',
    footTag:'{coin} معیشت کے لیے غیر مرکزی AI کمپیوٹ · پاکستان',
    sceneCap:'بادشاہی مسجد',
  },

  ar: {
    navCompute:'الحوسبة', navCoin:'{coin}', navCountry:'{country}', navDai:'DAI', navWallet:'المحفظة', navMiner:'مُعدِّن DAI',
    heroTitle:'حوسبة ذكاء اصطناعي لامركزية، تُدفع بـ{coin}',
    heroLede:'جهازك يحلّ مهام الذكاء الاصطناعي للشبكة ويتقاضى بـ{coin} — بلا مركز بيانات، بلا عقد سحابي، وبلا إذن من أحد.',
    s1Eyebrow:'ما هذا', s1Title:'شبكة تحسب.',
    s1aT:'لامركزية', s1aD:'عقد مستقلة، من ندٍّ إلى ند. لا شركة تملك الشبكة، ولا مفتاح مركزي يُطفئها.',
    s1bT:'مشفّرة وسيادية', s1bD:'المفاتيح لك. المحادثة مشفّرة من الطرف إلى الطرف، وبياناتك لا تغادر شروطك.',
    s1cT:'ادفع بحسب الاستخدام', s1cD:'تُقاس بكل رمز ذكاء اصطناعي مع سقف صارم للميزانية لكل مهمة. وتُعاد الميزانية غير المستخدمة.',
    s2Eyebrow:'طبقة الدفع', s2Title:'التسوية بـ{coin}.',
    s2aT:'{coin}', s2aD:'المسار المحلي. القيمة تتحرك بالعملة التي يكسبها الناس وينفقونها فعلاً.',
    s2bT:'DAI توفّر الحوسبة', s2bD:'حوسبة ذكاء اصطناعي لامركزية لذلك الاقتصاد، بتسعير وتسوية محليين.',
    s3Eyebrow:'لماذا هنا', s3Title:'صُنع في {country}.',
    s3aT:'طاقة في المتناول', s3aD:'الكهرباء هي التكلفة الحقيقية لحوسبة الذكاء الاصطناعي، وهي هنا رخيصة بما يكفي لترك هامش.',
    s3bT:'أناس يبنون', s3bD:'قوة عاملة شابة وتقنية قادرة على تشغيل العقد وكتابة المهارات التي تعمل عليها.',
    s3cT:'طلب محلي', s3cD:'ذكاء اصطناعي مسعّر بالعملة المحلية، في المتناول دون بطاقة أو مصرف أجنبي.',
    s3dT:'سيادية بالتصميم', s3dD:'العملة تبقى لك. والشبكة تسوّيها دون أن تستأذن أحداً.',
    s4Eyebrow:'السوق المحلي', s4Title:'{coin} تشتري الحوسبة.',
    s4Lede:'العملة الصعبة تُسوّى إلى {coin} — و{coin} تشتري حوسبة الذكاء الاصطناعي والكفاءات والخبرة المحلية في {country}.',
    s4In:'عملة داخلة', s4Rail:'العملة المستقرة لـ{country}', s4Out:'ما تحصل عليه',
    s4o1:'حوسبة ذكاء اصطناعي', s4o2:'كفاءات محلية', s4o3:'خبرة',
    s5Eyebrow:'التبادل', s5Title:'تداولها من ندٍّ إلى ند.',
    s5Lede:'بادل USDT و{coin} وبقية عملات الحوسبة في سوق P2P المفتوح. يُسوّى الطرفان على السلسلة خلال ثوانٍ.',
    s5Cta:'افتح سوق P2P',
    s6Eyebrow:'ابدأ', s6Title:'شغّل جهازك.',
    s6Lede:'شغّل عقدة. اكسب {coin}.',
    s6a:'تشغيل عقدة', s6b:'اقرأ الوثائق',
    footTag:'حوسبة ذكاء اصطناعي لامركزية لاقتصاد {coin} · {country}',
    sceneCap:'{landmark}',
  },

  pt: {
    navCompute:'Computação', navCoin:'{coin}', navCountry:'Angola', navDai:'DAI', navWallet:'Carteira', navMiner:'DAI Miner',
    heroTitle:'Computação de IA descentralizada, paga em {coin}',
    heroLede:'A sua máquina resolve tarefas de IA para a rede e recebe em {coin} — sem centro de dados, sem contrato de nuvem, sem pedir autorização.',
    s1Eyebrow:'O que é isto', s1Title:'Uma rede que computa.',
    s1aT:'Descentralizada', s1aD:'Nós independentes, ponto a ponto. Nenhuma empresa é dona da malha e não há interruptor central para desligar.',
    s1bT:'Cifrada e soberana', s1bD:'As chaves são suas. O chat é cifrado de ponta a ponta e os seus dados não saem dos seus termos.',
    s1cT:'Paga pelo uso', s1cD:'Medida por token de IA, com orçamento máximo por tarefa. O orçamento não usado é devolvido.',
    s2Eyebrow:'A camada de pagamento', s2Title:'Liquidado em {coin}.',
    s2aT:'{coin}', s2aD:'O trilho local. O valor circula na moeda que as pessoas realmente ganham e gastam.',
    s2bT:'A DAI fornece a computação', s2bD:'Computação de IA descentralizada para essa economia, com preço e liquidação locais.',
    s3Eyebrow:'Porquê aqui', s3Title:'Feito em Angola.',
    s3aT:'Energia acessível', s3aD:'A electricidade é o custo real da computação de IA e aqui é barata o suficiente para deixar margem.',
    s3bT:'Gente que constrói', s3bD:'Uma força de trabalho jovem e técnica, capaz de operar nós e escrever as habilidades que correm neles.',
    s3cT:'Procura local', s3cD:'IA cotada em moeda local, ao alcance sem cartão nem banco estrangeiro.',
    s3dT:'Soberana por concepção', s3dD:'A moeda continua sua. A rede liquida-a sem pedir autorização a ninguém.',
    s4Eyebrow:'O mercado local', s4Title:'{coin} compra computação.',
    s4Lede:'A moeda forte liquida em {coin} — e {coin} compra computação de IA, talento e experiência local em Angola.',
    s4In:'Divisa que entra', s4Rail:'Stablecoin de Angola', s4Out:'O que recebe',
    s4o1:'Computação de IA', s4o2:'Talento local', s4o3:'Experiência',
    s5Eyebrow:'Câmbio', s5Title:'Negoceie ponto a ponto.',
    s5Lede:'Troque USDT, {coin} e as outras moedas de computação no mercado P2P aberto. Ambas as pontas liquidam na chain em segundos.',
    s5Cta:'Abrir o mercado P2P',
    s6Eyebrow:'Começar', s6Title:'Ponha a sua máquina a trabalhar.',
    s6Lede:'Corra um nó. Ganhe {coin}.',
    s6a:'Correr um nó', s6b:'Ler a documentação',
    footTag:'Computação de IA descentralizada para a economia {coin} · Angola',
    sceneCap:'Quedas de Kalandula',
  },

  fa: {
    navCompute:'محاسبات', navCoin:'{coin}', navCountry:'ایران', navDai:'DAI', navWallet:'کیف پول', navMiner:'ماینر DAI',
    heroTitle:'محاسبات هوش مصنوعی غیرمتمرکز، پرداخت با {coin}',
    heroLede:'دستگاه شما کارهای هوش مصنوعی شبکه را انجام می‌دهد و با {coin} دستمزد می‌گیرد — بدون مرکز داده، بدون قرارداد ابری، بدون اجازه گرفتن از کسی.',
    s1Eyebrow:'این چیست', s1Title:'شبکه‌ای که محاسبه می‌کند.',
    s1aT:'غیرمتمرکز', s1aD:'نودهای مستقل، همتا به همتا. هیچ شرکتی مالک شبکه نیست و کلید مرکزی برای خاموش کردن آن وجود ندارد.',
    s1bT:'رمزنگاری‌شده و مستقل', s1bD:'کلیدها در دست شماست. گفتگو سرتاسر رمزنگاری شده و داده‌های شما از شرایط شما بیرون نمی‌رود.',
    s1cT:'پرداخت به‌ازای مصرف', s1cD:'بر پایه هر توکن هوش مصنوعی اندازه‌گیری می‌شود، با سقف بودجه برای هر کار. بودجه مصرف‌نشده بازگردانده می‌شود.',
    s2Eyebrow:'لایه پرداخت', s2Title:'تسویه با {coin}.',
    s2aT:'{coin}', s2aD:'ریل محلی. ارزش با همان پولی جابه‌جا می‌شود که مردم واقعاً به دست می‌آورند و خرج می‌کنند.',
    s2bT:'DAI محاسبات را فراهم می‌کند', s2bD:'محاسبات هوش مصنوعی غیرمتمرکز برای آن اقتصاد، با قیمت‌گذاری و تسویه محلی.',
    s3Eyebrow:'چرا اینجا', s3Title:'ساخته‌شده در ایران.',
    s3aT:'انرژی مقرون‌به‌صرفه', s3aD:'برق هزینه واقعی محاسبات هوش مصنوعی است و اینجا آن‌قدر ارزان است که حاشیه سود بماند.',
    s3bT:'مردمی که می‌سازند', s3bD:'نیروی جوان و فنی که می‌تواند نود اجرا کند و مهارت‌هایی بنویسد که روی آن اجرا می‌شوند.',
    s3cT:'تقاضای محلی', s3cD:'هوش مصنوعی با پول محلی قیمت‌گذاری می‌شود — بدون نیاز به کارت یا بانک خارجی.',
    s3dT:'مستقل در طراحی', s3dD:'سکه از آنِ شما می‌ماند. شبکه بدون اجازه گرفتن از کسی آن را تسویه می‌کند.',
    s4Eyebrow:'بازار محلی', s4Title:'{coin} محاسبات می‌خرد.',
    s4Lede:'ارز سخت به {coin} تسویه می‌شود — و {coin} در ایران محاسبات هوش مصنوعی، استعداد و تجربه محلی می‌خرد.',
    s4In:'ارز ورودی', s4Rail:'استیبل‌کوین ایران', s4Out:'آنچه می‌گیرید',
    s4o1:'محاسبات هوش مصنوعی', s4o2:'استعداد محلی', s4o3:'تجربه',
    s5Eyebrow:'تبادل', s5Title:'همتا به همتا معامله کنید.',
    s5Lede:'USDT، {coin} و دیگر سکه‌های محاسباتی را در بازار باز P2P مبادله کنید. هر دو طرف در چند ثانیه روی زنجیره تسویه می‌شوند.',
    s5Cta:'بازار P2P را باز کنید',
    s6Eyebrow:'شروع کنید', s6Title:'دستگاهتان را به کار بگیرید.',
    s6Lede:'یک نود اجرا کنید. {coin} به دست آورید.',
    s6a:'اجرای نود', s6b:'خواندن مستندات',
    footTag:'محاسبات هوش مصنوعی غیرمتمرکز برای اقتصاد {coin} · ایران',
    sceneCap:'تخت جمشید',
  },
  // Dzongkha (Tibetan script). Bhutan's national language.
  dz: {
    navCompute:'རྩིས་སྒྲུབ།', navCoin:'{coin}', navCountry:'འབྲུག', navDai:'DAI', navWallet:'དངུལ་སྒམ།', navMiner:'DAI གཏེར་སྐྲུན།',
    heroTitle:'དབུས་མེད་ AI རྩིས་སྒྲུབ། {coin} གིས་སྤྲོད།',
    heroLede:'ཁྱོད་ཀྱི་གློག་རིག་གིས་དྲ་བའི་དོན་ལུ་ AI ལས་ཀ་འབད་བཞིནམ་ལས་ {coin} ཐོབ། གནས་སྡུད་ལྟེ་བ་མེད། སྤྲིན་གྱི་གན་རྒྱ་མེད། གནང་བ་ཞུ་མི་དགོ།',
    s1Eyebrow:'འདི་ག་ཅི་སྨོ།', s1Title:'རྩིས་སྒྲུབ་འབད་མི་དྲ་བ།',
    s1aT:'དབུས་མེད།', s1aD:'རང་དབང་ཅན་གྱི་མཚམས་ཚུ། གཅིག་ལས་གཅིག། དྲ་བ་འདི་ཚོང་སྡེ་ག་གིས་ཡང་བདག་འཛིན་མི་འབད། བཀག་ནིའི་ལྟེ་བའི་མཐེབ་གཅུ་ཡང་མེད།',
    s1bT:'གསང་སྐུད་དང་རང་དབང་།', s1bD:'ལྡེ་མིག་ཚུ་ཁྱོད་ལུ་ཡོད། ཁ་བརྡ་འདི་མཐའ་ལས་མཐའ་ཚུན་གསང་སྐུད་འབད་ཡོདཔ་ལས་ ཁྱོད་ཀྱི་གནས་སྡུད་ཁྱོད་ཀྱི་གནས་སྟངས་ལས་ཕྱི་ཁར་མི་འགྱོ།',
    s1cT:'ལག་ལེན་དང་འཁྲིལ་ཏེ་སྤྲོད།', s1cD:'AI ཊོ་ཀཱན་རེ་རེ་བཞིན་དུ་ཚད་འཇལ་ཞིནམ་ལས་ ལས་ཀ་རེ་ལུ་མ་དངུལ་གྱི་ཚད་ངེས་ཅན་ཡོད། མ་ལག་ལེན་འཐབ་པའི་མ་དངུལ་འདི་ཕྱིར་སློག་འབད་ཨིན།',
    s2Eyebrow:'སྤྲོད་ལེན་གྱི་རིམ་པ།', s2Title:'{coin} ནང་གཏན་འཁེལ།',
    s2aT:'{coin}', s2aD:'ས་གནས་ཀྱི་ལམ། རིན་ཐང་འདི་མི་ཚུ་གིས་ངོ་མ་ཐོབ་ཞིནམ་ལས་གཏང་མི་དངུལ་ནང་འགྱོ།',
    s2bT:'DAI གིས་རྩིས་སྒྲུབ་བྱིན།', s2bD:'དཔལ་འབྱོར་དེ་གི་དོན་ལུ་དབུས་མེད་ AI རྩིས་སྒྲུབ། ས་གནས་ནང་རིན་གོང་བཟོ་ཞིནམ་ལས་གཏན་འཁེལ་འབདཝ་ཨིན།',
    s3Eyebrow:'ག་ཅི་འབད་ནཱ།', s3Title:'འབྲུག་ནང་བཟོ་བཟོཝ།',
    s3aT:'གོང་ཚད་འོས་འབབ་ཅན་གྱི་གློག', s3aD:'གློག་མེ་འདི་ AI རྩིས་སྒྲུབ་ཀྱི་གཙོ་བོའི་གླ་ཆ་ཨིནམ་ལས་ ནཱ་ལུ་ཁེ་ཕན་ལྷག་ལུས་ཚུགས་པའི་ཁེ་གོང་ཡོད།',
    s3bT:'བཟོ་སྐྲུན་འབད་མི་མི་ཚུ།', s3bD:'མཚམས་ཚུ་གཡོག་བཀོལ་ཞིནམ་ལས་ དེ་གུ་ལཱ་འབད་མི་རིག་རྩལ་འབྲི་ཚུགས་མི་ན་གཞོན་དང་འཕྲུལ་རིག་གི་ལས་མི།',
    s3cT:'ས་གནས་ཀྱི་དགོས་མཁོ།', s3cD:'AI འདི་ས་གནས་ཀྱི་དངུལ་ནང་རིན་གོང་བཟོཝ་ཨིན། ཕྱི་རྒྱལ་གྱི་ཤོག་བྱང་ཡང་ན་དངུལ་ཁང་མེད་པར་ལེན་ཚུགས།',
    s3dT:'བཀོད་སྒྲིག་ལས་རང་དབང་།', s3dD:'དངུལ་སྒོར་འདི་ཁྱོད་རང་གི་ཨིན། དྲ་བ་གིས་ག་ལས་ཡང་གནང་བ་མ་ཞུ་བར་གཏན་འཁེལ་འབདཝ་ཨིན།',
    s4Eyebrow:'ས་གནས་ཀྱི་ཁྲོམ།', s4Title:'{coin} གིས་རྩིས་སྒྲུབ་ཉོཝ་ཨིན།',
    s4Lede:'དངུལ་སྲ་བ་འདི་ {coin} ནང་གཏན་འཁེལ་འབདཝ་ཨིན། {coin} གིས་འབྲུག་ནང་ AI རྩིས་སྒྲུབ་དང་ ས་གནས་ཀྱི་རིག་རྩལ་ དེ་ལས་ཉམས་མྱོང་ཉོཝ་ཨིན།',
    s4In:'ནང་འཛུལ་དངུལ།', s4Rail:'འབྲུག་གི་བརྟན་དངུལ།', s4Out:'ཁྱོད་ཀྱིས་ཐོབ་མི།',
    s4o1:'AI རྩིས་སྒྲུབ།', s4o2:'ས་གནས་ཀྱི་རིག་རྩལ།', s4o3:'ཉམས་མྱོང་།',
    s5Eyebrow:'བརྗེ་སོར།', s5Title:'གཅིག་ལས་གཅིག་ཚོང་འབྲེལ།',
    s5Lede:'ཁ་ཕྱེ་བའི་ P2P ཁྲོམ་ནང་ USDT དང་ {coin} དེ་ལས་རྩིས་སྒྲུབ་ཀྱི་དངུལ་སྒོར་གཞན་ཚུ་བརྗེ་སོར་འབད། ཕྱོགས་གཉིས་ཆ་ར་སྐར་ཆ་ཁ་ཤས་ནང་ཅིང་གུ་གཏན་འཁེལ་འགྱོཝ་ཨིན།',
    s5Cta:'P2P ཁྲོམ་ཁ་ཕྱེ།',
    s6Eyebrow:'འགོ་བཙུགས།', s6Title:'ཁྱོད་ཀྱི་གློག་རིག་ལཱ་ནང་བཙུགས།',
    s6Lede:'མཚམས་གཅིག་གཡོག་བཀོལ། {coin} ཐོབ།',
    s6a:'མཚམས་གཡོག་བཀོལ།', s6b:'ཡིག་ཆ་ལྷག',
    footTag:'{coin} དཔལ་འབྱོར་གྱི་དོན་ལུ་དབུས་མེད་ AI རྩིས་སྒྲུབ། · འབྲུག',
    sceneCap:'སྤ་རོ་སྟག་ཚང་།',
  },
};

export function L(lang, c) {
  const base = T.en;
  const tbl = T[lang] || base;
  const fill = (s) => String(s)
    .replaceAll('{country}', c.country)
    .replaceAll('{coin}', c.coin)
    .replaceAll('{landmark}', c.landmark);
  const out = {};
  for (const k of Object.keys(base)) out[k] = fill(tbl[k] != null ? tbl[k] : base[k]);
  return out;
}

export const TABLES = T;
export const KEYS = Object.keys(T.en);
